name: Manual Ad Publisher

on:
  workflow_dispatch:

jobs:
  publish-ad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ad generation script
        run: python generate_ad_page.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 발행 기록 파일과 새로 생성된 HTML 파일을 모두 Git에 추가
          git add ads/
          git add published_offers.json # 발행 기록 파일도 반드시 추가
          
          # 변경사항이 없으면 커밋 건너뛰기
          git commit -m "feat: Publish new ad campaign" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
